//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace misOfertas.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CAMPANA> CAMPANA { get; set; }
        public DbSet<CUPON> CUPON { get; set; }
        public DbSet<EMPRESA> EMPRESA { get; set; }
        public DbSet<MAILLIST> MAILLIST { get; set; }
        public DbSet<OFERTA> OFERTA { get; set; }
        public DbSet<PRODUCTO> PRODUCTO { get; set; }
        public DbSet<PUNTOS> PUNTOS { get; set; }
        public DbSet<RECUPERARPWUSER> RECUPERARPWUSER { get; set; }
        public DbSet<ROL_USUARIO> ROL_USUARIO { get; set; }
        public DbSet<RUBRO> RUBRO { get; set; }
        public DbSet<TIENDA> TIENDA { get; set; }
        public DbSet<TRAMO> TRAMO { get; set; }
        public DbSet<USUARIO> USUARIO { get; set; }
        public DbSet<VALORACION> VALORACION { get; set; }
        public DbSet<USUARIOSMAILIST> USUARIOSMAILIST { get; set; }
    
        public virtual int addEmpresa(string p_NOMBRE_EMPRESA, string p_RAZON_SOCIAL, string p_ESTADO, string p_RUT)
        {
            var p_NOMBRE_EMPRESAParameter = p_NOMBRE_EMPRESA != null ?
                new ObjectParameter("P_NOMBRE_EMPRESA", p_NOMBRE_EMPRESA) :
                new ObjectParameter("P_NOMBRE_EMPRESA", typeof(string));
    
            var p_RAZON_SOCIALParameter = p_RAZON_SOCIAL != null ?
                new ObjectParameter("P_RAZON_SOCIAL", p_RAZON_SOCIAL) :
                new ObjectParameter("P_RAZON_SOCIAL", typeof(string));
    
            var p_ESTADOParameter = p_ESTADO != null ?
                new ObjectParameter("P_ESTADO", p_ESTADO) :
                new ObjectParameter("P_ESTADO", typeof(string));
    
            var p_RUTParameter = p_RUT != null ?
                new ObjectParameter("P_RUT", p_RUT) :
                new ObjectParameter("P_RUT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addEmpresa", p_NOMBRE_EMPRESAParameter, p_RAZON_SOCIALParameter, p_ESTADOParameter, p_RUTParameter);
        }
    
        public virtual int sp_InsertMailL(string p_SUSCRITO, Nullable<decimal> p_USUARIO_FK)
        {
            var p_SUSCRITOParameter = p_SUSCRITO != null ?
                new ObjectParameter("P_SUSCRITO", p_SUSCRITO) :
                new ObjectParameter("P_SUSCRITO", typeof(string));
    
            var p_USUARIO_FKParameter = p_USUARIO_FK.HasValue ?
                new ObjectParameter("P_USUARIO_FK", p_USUARIO_FK) :
                new ObjectParameter("P_USUARIO_FK", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertMailL", p_SUSCRITOParameter, p_USUARIO_FKParameter);
        }
    
        public virtual int login(string p_CORREO, string p_CONTRASENA, ObjectParameter nOMBRE_ROL)
        {
            var p_CORREOParameter = p_CORREO != null ?
                new ObjectParameter("P_CORREO", p_CORREO) :
                new ObjectParameter("P_CORREO", typeof(string));
    
            var p_CONTRASENAParameter = p_CONTRASENA != null ?
                new ObjectParameter("P_CONTRASENA", p_CONTRASENA) :
                new ObjectParameter("P_CONTRASENA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("login", p_CORREOParameter, p_CONTRASENAParameter, nOMBRE_ROL);
        }
    
        public virtual int addValoracion(Nullable<System.DateTime> p_FECHA, string p_IMAGEN, Nullable<decimal> p_CALIDAD, Nullable<decimal> p_ATENCION, Nullable<decimal> p_PRECIO, string p_COMENTARIO, Nullable<decimal> p_USUARIO_FK, Nullable<decimal> p_OFERTA_FK)
        {
            var p_FECHAParameter = p_FECHA.HasValue ?
                new ObjectParameter("P_FECHA", p_FECHA) :
                new ObjectParameter("P_FECHA", typeof(System.DateTime));
    
            var p_IMAGENParameter = p_IMAGEN != null ?
                new ObjectParameter("P_IMAGEN", p_IMAGEN) :
                new ObjectParameter("P_IMAGEN", typeof(string));
    
            var p_CALIDADParameter = p_CALIDAD.HasValue ?
                new ObjectParameter("P_CALIDAD", p_CALIDAD) :
                new ObjectParameter("P_CALIDAD", typeof(decimal));
    
            var p_ATENCIONParameter = p_ATENCION.HasValue ?
                new ObjectParameter("P_ATENCION", p_ATENCION) :
                new ObjectParameter("P_ATENCION", typeof(decimal));
    
            var p_PRECIOParameter = p_PRECIO.HasValue ?
                new ObjectParameter("P_PRECIO", p_PRECIO) :
                new ObjectParameter("P_PRECIO", typeof(decimal));
    
            var p_COMENTARIOParameter = p_COMENTARIO != null ?
                new ObjectParameter("P_COMENTARIO", p_COMENTARIO) :
                new ObjectParameter("P_COMENTARIO", typeof(string));
    
            var p_USUARIO_FKParameter = p_USUARIO_FK.HasValue ?
                new ObjectParameter("P_USUARIO_FK", p_USUARIO_FK) :
                new ObjectParameter("P_USUARIO_FK", typeof(decimal));
    
            var p_OFERTA_FKParameter = p_OFERTA_FK.HasValue ?
                new ObjectParameter("P_OFERTA_FK", p_OFERTA_FK) :
                new ObjectParameter("P_OFERTA_FK", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addValoracion", p_FECHAParameter, p_IMAGENParameter, p_CALIDADParameter, p_ATENCIONParameter, p_PRECIOParameter, p_COMENTARIOParameter, p_USUARIO_FKParameter, p_OFERTA_FKParameter);
        }
    
        public virtual int addTienda(string p_NOMBRE_TIENDA, string p_DIRECCION, string p_ESTADO, Nullable<decimal> p_EMPRESA_FK, Nullable<decimal> p_USUARIO_FK)
        {
            var p_NOMBRE_TIENDAParameter = p_NOMBRE_TIENDA != null ?
                new ObjectParameter("P_NOMBRE_TIENDA", p_NOMBRE_TIENDA) :
                new ObjectParameter("P_NOMBRE_TIENDA", typeof(string));
    
            var p_DIRECCIONParameter = p_DIRECCION != null ?
                new ObjectParameter("P_DIRECCION", p_DIRECCION) :
                new ObjectParameter("P_DIRECCION", typeof(string));
    
            var p_ESTADOParameter = p_ESTADO != null ?
                new ObjectParameter("P_ESTADO", p_ESTADO) :
                new ObjectParameter("P_ESTADO", typeof(string));
    
            var p_EMPRESA_FKParameter = p_EMPRESA_FK.HasValue ?
                new ObjectParameter("P_EMPRESA_FK", p_EMPRESA_FK) :
                new ObjectParameter("P_EMPRESA_FK", typeof(decimal));
    
            var p_USUARIO_FKParameter = p_USUARIO_FK.HasValue ?
                new ObjectParameter("P_USUARIO_FK", p_USUARIO_FK) :
                new ObjectParameter("P_USUARIO_FK", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addTienda", p_NOMBRE_TIENDAParameter, p_DIRECCIONParameter, p_ESTADOParameter, p_EMPRESA_FKParameter, p_USUARIO_FKParameter);
        }
    
        public virtual int addOferta(Nullable<decimal> p_CANTIDAD_MINIMA, Nullable<decimal> p_CANTIDAD_MAXIMA, Nullable<decimal> p_PRECIO_NORMAL, Nullable<decimal> p_PRECIO_OFERTA, string p_IMAGEN, Nullable<System.DateTime> p_FECHA, Nullable<decimal> p_CAMPANA_FK, Nullable<decimal> p_PRODUCTO_FK)
        {
            var p_CANTIDAD_MINIMAParameter = p_CANTIDAD_MINIMA.HasValue ?
                new ObjectParameter("P_CANTIDAD_MINIMA", p_CANTIDAD_MINIMA) :
                new ObjectParameter("P_CANTIDAD_MINIMA", typeof(decimal));
    
            var p_CANTIDAD_MAXIMAParameter = p_CANTIDAD_MAXIMA.HasValue ?
                new ObjectParameter("P_CANTIDAD_MAXIMA", p_CANTIDAD_MAXIMA) :
                new ObjectParameter("P_CANTIDAD_MAXIMA", typeof(decimal));
    
            var p_PRECIO_NORMALParameter = p_PRECIO_NORMAL.HasValue ?
                new ObjectParameter("P_PRECIO_NORMAL", p_PRECIO_NORMAL) :
                new ObjectParameter("P_PRECIO_NORMAL", typeof(decimal));
    
            var p_PRECIO_OFERTAParameter = p_PRECIO_OFERTA.HasValue ?
                new ObjectParameter("P_PRECIO_OFERTA", p_PRECIO_OFERTA) :
                new ObjectParameter("P_PRECIO_OFERTA", typeof(decimal));
    
            var p_IMAGENParameter = p_IMAGEN != null ?
                new ObjectParameter("P_IMAGEN", p_IMAGEN) :
                new ObjectParameter("P_IMAGEN", typeof(string));
    
            var p_FECHAParameter = p_FECHA.HasValue ?
                new ObjectParameter("P_FECHA", p_FECHA) :
                new ObjectParameter("P_FECHA", typeof(System.DateTime));
    
            var p_CAMPANA_FKParameter = p_CAMPANA_FK.HasValue ?
                new ObjectParameter("P_CAMPANA_FK", p_CAMPANA_FK) :
                new ObjectParameter("P_CAMPANA_FK", typeof(decimal));
    
            var p_PRODUCTO_FKParameter = p_PRODUCTO_FK.HasValue ?
                new ObjectParameter("P_PRODUCTO_FK", p_PRODUCTO_FK) :
                new ObjectParameter("P_PRODUCTO_FK", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addOferta", p_CANTIDAD_MINIMAParameter, p_CANTIDAD_MAXIMAParameter, p_PRECIO_NORMALParameter, p_PRECIO_OFERTAParameter, p_IMAGENParameter, p_FECHAParameter, p_CAMPANA_FKParameter, p_PRODUCTO_FKParameter);
        }
    
        public virtual int addUsuario(string p_NOMBRES_USUARIO, string p_APELLIDO_PATERNO, string p_APELLIDO_MATERNO, string p_CORREO, string p_CONTRASENA, string p_RUT, string p_ESTADO, Nullable<System.DateTime> p_FECHA, Nullable<decimal> p_ROL_USUARIO_FK)
        {
            var p_NOMBRES_USUARIOParameter = p_NOMBRES_USUARIO != null ?
                new ObjectParameter("P_NOMBRES_USUARIO", p_NOMBRES_USUARIO) :
                new ObjectParameter("P_NOMBRES_USUARIO", typeof(string));
    
            var p_APELLIDO_PATERNOParameter = p_APELLIDO_PATERNO != null ?
                new ObjectParameter("P_APELLIDO_PATERNO", p_APELLIDO_PATERNO) :
                new ObjectParameter("P_APELLIDO_PATERNO", typeof(string));
    
            var p_APELLIDO_MATERNOParameter = p_APELLIDO_MATERNO != null ?
                new ObjectParameter("P_APELLIDO_MATERNO", p_APELLIDO_MATERNO) :
                new ObjectParameter("P_APELLIDO_MATERNO", typeof(string));
    
            var p_CORREOParameter = p_CORREO != null ?
                new ObjectParameter("P_CORREO", p_CORREO) :
                new ObjectParameter("P_CORREO", typeof(string));
    
            var p_CONTRASENAParameter = p_CONTRASENA != null ?
                new ObjectParameter("P_CONTRASENA", p_CONTRASENA) :
                new ObjectParameter("P_CONTRASENA", typeof(string));
    
            var p_RUTParameter = p_RUT != null ?
                new ObjectParameter("P_RUT", p_RUT) :
                new ObjectParameter("P_RUT", typeof(string));
    
            var p_ESTADOParameter = p_ESTADO != null ?
                new ObjectParameter("P_ESTADO", p_ESTADO) :
                new ObjectParameter("P_ESTADO", typeof(string));
    
            var p_FECHAParameter = p_FECHA.HasValue ?
                new ObjectParameter("P_FECHA", p_FECHA) :
                new ObjectParameter("P_FECHA", typeof(System.DateTime));
    
            var p_ROL_USUARIO_FKParameter = p_ROL_USUARIO_FK.HasValue ?
                new ObjectParameter("P_ROL_USUARIO_FK", p_ROL_USUARIO_FK) :
                new ObjectParameter("P_ROL_USUARIO_FK", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addUsuario", p_NOMBRES_USUARIOParameter, p_APELLIDO_PATERNOParameter, p_APELLIDO_MATERNOParameter, p_CORREOParameter, p_CONTRASENAParameter, p_RUTParameter, p_ESTADOParameter, p_FECHAParameter, p_ROL_USUARIO_FKParameter);
        }
    }
}
