//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace misOfertas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECUPERARPWUSER
    {
        public decimal ID_RECUPERARPWUSER { get; set; }
        public string USER_CORREO { get; set; }
        public string RESPUESTA_SEGURIDAD { get; set; }
    }
}
