//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace misOfertas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIOSMAILIST
    {
        public string NOMBRES_USUARIO { get; set; }
        public string APELLIDO_PATERNO { get; set; }
        public string CORREO { get; set; }
    }
}
